-- Insert initial categories
INSERT INTO categories (name, description, slug, color) VALUES
('Forældreskab', 'Generelle råd og ressourcer om forældreskab', 'foraeldre', '#3B82F6'),
('Sundhed & Trivsel', 'Sundhed, motion og mental trivsel for fædre', 'sundhed', '#10B981'),
('Aktiviteter', 'Aktiviteter og oplevelser med børn', 'aktiviteter', '#F59E0B'),
('Uddannelse', 'Læringsressourcer og uddannelsesmateriale', 'uddannelse', '#8B5CF6'),
('Økonomi', 'Familieøkonomi og finansiel planlægning', 'oekonomi', '#EF4444'),
('Teknologi', 'Apps, værktøjer og teknologi til fædre', 'teknologi', '#6B7280'),
('Karriere', 'Balance mellem arbejde og familieliv', 'karriere', '#EC4899'),
('Fritid & Hobbyer', 'Personlige interesser og hobbyer', 'fritid', '#14B8A6');

-- Insert initial tags
INSERT INTO tags (name, slug) VALUES
('baby', 'baby'),
('småbørn', 'smaboern'),
('teenagere', 'teenagere'),
('motion', 'motion'),
('mad', 'mad'),
('søvn', 'soevn'),
('disciplin', 'disciplin'),
('kommunikation', 'kommunikation'),
('leg', 'leg'),
('udendørs', 'udendoers'),
('indendørs', 'indendoers'),
('kreativitet', 'kreativitet'),
('læring', 'laering'),
('matematik', 'matematik'),
('læsning', 'laesning'),
('sprog', 'sprog'),
('videnskab', 'videnskab'),
('historie', 'historie'),
('opsparing', 'opsparing'),
('budget', 'budget'),
('investering', 'investering'),
('forsikring', 'forsikring'),
('apps', 'apps'),
('værktøjer', 'vaerktojer'),
('sikkerhed', 'sikkerhed'),
('arbejde-liv-balance', 'arbejde-liv-balance'),
('hjemmearbejde', 'hjemmearbejde'),
('stress', 'stress'),
('sport', 'sport'),
('musik', 'musik'),
('film', 'film'),
('bøger', 'boeger'),
('rejser', 'rejser'),
('ferie', 'ferie'),
('traditioner', 'traditioner'),
('højtider', 'hoejtider');