# Nixpacks configuration for Farlandet.dk
providers = ["node"]

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = ["npm ci", "cd server && npm ci"]

[phases.build]
cmds = ["npm run build:prod", "cd server && npm run build"]

[start]
# Use the production startup script for reliable deployment
cmd = "npm start"