# Simple Nixpacks configuration for Farlandet.dk
providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server.js"