[providers]
node = "20.15.0"

[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --only=production=false",
  "npm install -g serve"
]

[phases.build]
cmds = [
  "npm run build:prod"
]

[start]
cmd = "npm start"