# Nixpacks configuration for Farlandet.dk
providers = ["node"]

[variables]
NODE_ENV = "production"
NODE_VERSION = "20"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build:prod"]

[start]
cmd = "npx serve -s dist -l ${PORT:-3000}"